# http://travis-ci.org/#!/mozilla/crontabber

language: python

python:
    - 2.6
    - 2.7

addons:
    postgresql: "9.2"

before_install:
    - pip install -r test-requirements.txt
    - psql -c 'create database travis_ci_test;' -U postgres

install:
    - python setup.py install

script:
    - user=postgres dbname=travis_ci_test nosetests crontabber --with-cover --cover-erase --cover-package=crontabber

notifications:
    irc:
        channels: "irc.mozilla.org#breakpad"

after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls --use-mirrors
    - coveralls

deploy:
    provider: pypi
    user: peterbe
    password:
        secure: pLLUb5KUKlK+/G05WxbWhv0TCBqtsdgK6FylIca1EkfvVeVSEZzbL/ptSKt47cIUypm6tkbcG2QE1FzCD/Oj/JnttJyQg0UMOFnobbYqaldgDYi6LXNejG4/5SqNkMu0yabkcK0nKx2s614lCAUypvWZrX5KYh61vHT/+Asxqek=
    on:
        repo: mozilla/crontabber
        branch: master
    distributions: "sdist bdist_wheel"
